
[[plugins]]
repo = 'ryanoasis/vim-devicons'


[[plugins]]
repo = 'kristijanhusak/vim-hybrid-material'

[[plugins]]
repo = 'hardcoreplayers/oceanic-material'

[[plugins]]
repo = 'arcticicestudio/nord-vim'

[[plugins]]
repo = 'rakr/vim-one'

[[plugins]]
repo = 'dracula/vim'

[[plugins]]
repo = 'drewtempelmeyer/palenight.vim'

[[plugins]]
repo = 'ayu-theme/ayu-vim'

[[plugins]]
repo = 'joshdick/onedark.vim'

[[plugins]]
repo = 'gruvbox-community/gruvbox'

[[plugins]]
repo = 'nanotech/jellybeans.vim'

[[plugins]]
repo = 'mhartington/oceanic-next'

[[plugins]]
repo = 'chriskempson/base16-vim'

[[plugins]]
repo = 'NLKNguyen/papercolor-theme'

[[plugins]]
repo = 'lifepillar/vim-gruvbox8'

[[plugins]]
repo = 'lifepillar/vim-solarized8'

[[plugins]]
repo = 'crusoexia/vim-monokai'

[[plugins]]
repo = 'hardcoreplayers/dashboard-nvim'

[[plugins]]
repo = 'hardcoreplayers/vim-buffet'
on_event = ['BufReadPre','BufNewFile']

[[plugins]]
repo = 'hardcoreplayers/spaceline.vim'
hook_source = '''
	let g:spaceline_seperate_style= 'slant'
'''

[[plugins]]
repo = 'powerline/powerline'

[[plugins]]
repo = 'adelarsq/vim-devicons-emoji'
